<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>stish</string>
	</array>
	<key>name</key>
	<string>Stish</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^(\${1,2})\s*(.+)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.ps1</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>text.stish.command</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^</string>
			<key>name</key>
			<string>meta.stish.prompt</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^#.+$</string>
			<key>name</key>
			<string>comment</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>stish</string>
	<key>uuid</key>
	<string>AF8D3707-011E-11E2-9804-705681C14B6F</string>
</dict>
</plist>
